version: "3.8"

services:
  app:
    build: .
    container_name: note-app-docker
    ports:
      - "5173:5173"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run docker
